---

- name: Create home directory
  ansible.builtin.file:
    path: "{{ ansiblenode_user_home }}"
    state: directory
    mode: "0700"

- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ ansiblenode_user_home }}/.ssh"
    state: directory
    mode: "0700"

- name: Change home directory
  ansible.builtin.file:
    path: "{{ ansiblenode_user_home }}"
    state: directory
    owner: "{{ ansiblenode_user_name }}"
    group: "{{ ansiblenode_group_name }}"
    recurse: yes

- name: Activate sudo
  ansible.builtin.template:
    src: "{{ 'sudo-nopasswd.j2' if ansiblenode_sudo_passwordless | bool else 'sudo-passwd.j2' }}"
    dest: /etc/sudoers.d/{{ ansiblenode_user_name }}
    mode: "0440"
  when: ansiblenode_sudo | bool

- name: Setup pubkey authentication for {{ ansiblenode_user_name }}
  ansible.posix.authorized_key:
    user: "{{ ansiblenode_user_name }}"
    state: present
    key: "{{ ansiblenode_pubkey }}"
  loop: "{{ ansiblenode_pubkeys }}"
  loop_control:
    loop_var: ansiblenode_pubkey
