---

- name: Setup prerequisits
  ansible.builtin.include_tasks: prereqs.yml
  when: ansiblenode_install_prereqs | bool

- name: Setup ansible user
  ansible.builtin.include_tasks:
    file: "{{ 'local-user.yml' if ansiblenode_local_user | bool else 'external-user.yml' }}"

- name: Setup user
  ansible.builtin.include_tasks: all-users.yml
