---

- name: Setup EPEL
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
  block:

    - name: Set facts
      ansible.builtin.include_role:
        name: deitkrachten.facts

    - name: Setup EPEL
      ansible.builtin.include_role:
        name: deitkrachten.epel

- name: Setup python
  ansible.builtin.include_role:
    name: deitkrachten.python
  vars:
    python_package_install_optional: false
    python_virtualenvs: []
