---

- name: deitkrachten.epel
  src: https://github.com/de-it-krachten/ansible-role-epel.git
  version: main
  scm: git
- name: deitkrachten.python
  src: https://github.com/de-it-krachten/ansible-role-python.git
  version: main
  scm: git
