---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    ansiblenode_install_prereqs: True
  tasks:
    - name: Include role 'ansible-role-ansiblenode'
      ansible.builtin.include_role:
        name: ansible-role-ansiblenode
